version: "3"
services:
  db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    networks:
      - webnet
  express:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: express
    depends_on:
      - db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8083:8083"
    networks:
      - webnet
networks:
  webnet:
    external: true