version: "3"
services:
  mongo-db:
    image: mongo
    restart: always
    ports:
      - 32768:27017
    networks:
      - webnet
  mongo-api0:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: montest
    volumes:
      - ./:/app
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8094:8094"
    environment:
      - MONGO_URL=mongodb://mongo-db:27017/app_development
      - EXPRESS_PORT=8094
    links:
      - mongo-db
    networks:
      - webnet
networks:
  webnet:
    external: true