version: "3"
services:
  geth:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: eth
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    volumes:
      - ~/ethereum:/root
    ports:
      - "8545:8545"
      - "30303:30303"
    networks:
      - webnet
networks:
  webnet:
    external: true