version: "3"
services:
  fatch:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: fatch
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8084:8084"
    networks:
      - webnet
networks:
  webnet:
    external: true