version: "3"
services:
  
  myside:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: myside
    volumes:
      - ./:/app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8100:8100"
    external_links:
      - mongodb_mongo_db_1
    environment:
      - MONGO_URL=mongodb://mongo-db:27017/app_development
      - EXPRESS_PORT=8100
    networks:
      - webnet
networks:
  webnet:
    external: true